name: Parque API images

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push register app
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./backend/parquet_api/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/parquet-api:latest
