name: Frontend images

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push streamlit
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./frontend/streamlit/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bluebird-streamlit:latest

      - name: Build and push front
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./frontend/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bluebird-next:latest

      
